name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-latest, windows-latest]

    steps:
      - name: Cancel previous runs on the same branch
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'

      - name: Prepare python
        run: |
          python -m pip install --upgrade pip

      - name: Set up QEMU
        if: startsWith(matrix.os, 'ubuntu')
        uses: docker/setup-qemu-action@v1
        with:
          platforms: 'arm64'

      - name: Build source distribution with Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          pip install build
          python -m build --sdist --outdir dist .

      - name: Build ${{ matrix.os }} wheels and test (old)
        uses: joerick/cibuildwheel@v1.11.1
        with:
          output-dir: dist
        env:
          # build just supported python versions at December 2021
          CIBW_BUILD: 'cp27-* cp35-* cp36-* pp27-* pp36-*'
          # Skip 32-bit builds // NO
          # CIBW_SKIP: '*-win32 *_i686'
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MUSLLINUX_I686_IMAGE: musllinux_1_1
          CIBW_MUSLLINUX_X86_64_IMAGE: musllinux_1_1
          # Only build on x86 and arm64 for linux
          CIBW_ARCHS_LINUX: i686 x86_64
          CIBW_BEFORE_ALL_LINUX: >
            python -m pip install --upgrade pip
          # CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          # Building two wheels for MacOS and skipping Universal
          CIBW_ARCHS_MACOS: x86_64
          # Skip testing Apple Silicon until there are GH runners
          CIBW_TEST_SKIP: '*_arm64 *_universal2:arm64'
          CIBW_BEFORE_ALL_MACOS: >
            python -m pip install --upgrade pip
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.14
          CIBW_BUILD_VERBOSITY_MACOS: 0
          CIBW_BEFORE_ALL_WINDOWS: >
            python -m pip install --upgrade pip
          CIBW_TEST_COMMAND: >
            python -m unittest discover -v -s {package}

      - name: Build ${{ matrix.os }} wheels and test (new)
        uses: joerick/cibuildwheel@v2.11.1
        with:
          output-dir: dist
        env:
          # build just supported python versions at December 2021
          CIBW_BUILD: 'cp37-* cp38-* cp39-* cp310-* cp311-* pp37-* pp38-* pp39-*'
          # Skip 32-bit builds // NO
          # CIBW_SKIP: '*-win32 *_i686'
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
          CIBW_MUSLLINUX_I686_IMAGE: musllinux_1_1
          CIBW_MUSLLINUX_X86_64_IMAGE: musllinux_1_1
          # Only build on x86 and arm64 for linux
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_BEFORE_ALL_LINUX: >
            python -m pip install --upgrade pip
          # CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          # Building two wheels for MacOS and skipping Universal
          CIBW_ARCHS_MACOS: x86_64 arm64
          # Skip testing Apple Silicon until there are GH runners
          CIBW_TEST_SKIP: '*_arm64 *_universal2:arm64'
          CIBW_BEFORE_ALL_MACOS: >
            python -m pip install --upgrade pip
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.14
          CIBW_BUILD_VERBOSITY_MACOS: 0
          CIBW_BEFORE_ALL_WINDOWS: >
            python -m pip install --upgrade pip
          CIBW_TEST_COMMAND: >
            python -m unittest discover -v -s {package}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist

      - name: Test for secrets access
        id: check_secrets
        # If a third party makes a pull request
        # this allows automated steps below to be skipped
        # and leave a clean PR CI run
        shell: bash
        run: |
          unset HAS_SECRET
          unset HAS_SECRET_TEST
          if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
          if [ -n "$SECRET_TEST" ]; then HAS_SECRET_TEST='true' ; fi
          echo ::set-output name=HAS_SECRET::${HAS_SECRET}
          echo ::set-output name=HAS_SECRET_TEST::${HAS_SECRET_TEST}
        env:
          SECRET: "${{ secrets.pypi_password }}"
          SECRET_TEST: "${{ secrets.test_pypi_password }}"

      - name: Install twine
        run: pip install twine

      - name: Publish distribution to PyPI
        if: >
         startsWith(github.event.ref, 'refs/tags') &&
         steps.check_secrets.outputs.HAS_SECRET
        env:
          # If the PR/Push has secret access
          # and PYPI_PASSWORD is in GH Secrets for this repo
          # and this is a tag, publish to PyPI
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
          TWINE_USERNAME: "${{ secrets.pypi_username }}"
          TWINE_NON_INTERACTIVE: 1
          TWINE_PASSWORD: "${{ secrets.pypi_password }}"
        run: twine upload --non-interactive --skip-existing --verbose 'dist/*'

      - name: Publish distribution to Test PyPI
        if: steps.check_secrets.outputs.HAS_SECRET
        env:
          # If the PR/Push has secret access
          # and TEST_PYPI_PASSWORD is in GH Secrets for this repo
          # then publish each build to test PyPI
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
          TWINE_USERNAME: "${{ secrets.test_pypi_username }}"
          TWINE_NON_INTERACTIVE: 1
          TWINE_PASSWORD: "${{ secrets.test_pypi_password }}"
        run: twine upload --non-interactive --skip-existing --verbose 'dist/*'
